### ISSUE TITLE
Duplicate entity exist

### ISSUE THREAD

**Issue by anubhavpulkit** [swiftlysingh/Holder#6]
**Describe the bug**
Duplicate cards exist after edits in Card type.

**To Reproduce**
1. Go to any card from CREDIT or DEBIT
2. Click on `Edit`
3. Click on  'Card type and change the type'
4. Go back to home and you can find same card exits in debit and credit group.
4'. Repeat the process again 1...4 and you can find multiple cards exit on debit card group of same specs.

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [iPhone 11]
 - OS: [iOS 17.0.3]

**Comment by swiftlysingh** [comment]
Which version of the App are you using? I am unable to reproduce this on production app.

**Comment by anubhavpulkit** [comment]
> Which version of the App are you using? I am unable to reproduce this on production app.

Develop branch build
